[package]
name = "versatiles_derive"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.93", features = ["proc-macro"] }
quote = { version = "1.0.38", features = ["proc-macro"] }
syn = { version = "2.0.98", features = ["extra-traits", "derive", "parsing", "printing", "proc-macro"] }
